import type { AccountRole } from "@/lib/auth/roles";
import type { InteractiveMessagePayload } from "@/lib/whatsapp/interactive";

export type {
  InteractiveMessagePayload,
  InteractiveButtonsPayload,
  InteractiveListPayload,
  InteractiveButton,
  InteractiveListRow,
  InteractiveListSection,
} from "@/lib/whatsapp/interactive";

export interface Profile {
  id: string;
  user_id: string;
  full_name: string;
  email: string;
  avatar_url?: string;
  /**
   * Legacy free-form role column from migration 001. Never read
   * by the app since 017_account_sharing.sql introduced the typed
   * `account_role` enum. Flagged for removal in a later cleanup
   * migration — kept on the type so existing destructures don't
   * break.
   */
  role: string;
  /**
   * Opted-in beta feature keys for this account. The column survives
   * for future beta gates; no current feature reads it (Flows was
   * the last user and went to soft-GA in PR #134). Defaults to `[]`
   * for every profile; toggled per-account via a direct UPDATE on
   * the `profiles` row.
   */
  beta_features?: string[];
  /**
   * Account this profile is a member of. Added by
   * `017_account_sharing.sql`; NOT NULL in the DB post-backfill.
   * Optional on the type only because older serialised payloads
   * (cached client state, test fixtures) may not have it yet.
   */
  account_id?: string;
  /**
   * Caller's role within their account. Source of truth for every
   * role-gated UI / API check — call `hasMinRole` from
   * `@/lib/auth/roles` rather than comparing this string directly.
   */
  account_role?: AccountRole;
  created_at: string;
}

// ============================================================
// Account-sharing entities (017_account_sharing.sql)
// ============================================================

export interface Account {
  id: string;
  name: string;
  /** auth.users.id of the immutable owner. */
  owner_user_id: string;
  created_at: string;
  updated_at: string;
}

/**
 * Hydrated member row for the Settings → Members tab. Combines
 * the profile and its account_role for a single member of the
 * caller's account. Sensitive fields (email) are populated only
 * when the caller has admin+ — agents and viewers see name +
 * avatar + role only.
 */
export interface AccountMember {
  user_id: string;
  full_name: string;
  email: string | null;
  avatar_url: string | null;
  role: AccountRole;
  joined_at: string;
}

/**
 * Outstanding invite link row. `token_hash` is intentionally
 * absent — it lives only in the DB and on the server. The
 * plaintext token is returned once at creation time and surfaced
 * via the invite URL; never re-emitted.
 */
export interface AccountInvitation {
  id: string;
  account_id: string;
  /** Roles offered via invite — owner is never offered. */
  role: Exclude<AccountRole, "owner">;
  created_by_user_id: string | null;
  label: string | null;
  created_at: string;
  expires_at: string;
  accepted_at: string | null;
  accepted_by_user_id: string | null;
}

export type LeadTemperature = 'cold' | 'warm' | 'hot';

export interface Contact {
  id: string;
  user_id: string;
  account_id: string;
  /** Nullable since migration 039 — Instagram-only contacts have no phone (they carry `instagram_id` instead). */
  phone: string | null;
  /** Digits-only form of `phone`, generated by the DB (migration 022)
   *  and unique per account. Read-only. */
  phone_normalized?: string;
  /**
   * Instagram-Scoped ID (migration 039). Set only for contacts that
   * came from Instagram — `phone` and `instagram_id` are mutually
   * exclusive by construction (see 039's comment). `phone` staying
   * required here (not yet optional) is intentional for this phase —
   * see docs/instagram-integration/PROGRESS.md, Phase 9.
   */
  instagram_id?: string;
  instagram_username?: string;
  /** Page-Scoped ID (migration 041) — set only for contacts that came
   *  from Facebook Messenger, same mutual-exclusivity pattern as
   *  `instagram_id`. */
  facebook_id?: string;
  facebook_username?: string;
  name?: string;
  email?: string;
  company?: string;
  /** Manual commercial qualification. Null/absent means not classified yet. */
  lead_temperature?: LeadTemperature | null;
  /** First-touch Meta ad/post referral captured on contact creation
   *  ({source,type,ad_id,ref}). Null for organic / non-Meta contacts
   *  and any created before migration 098. See `contacts.referral`. */
  referral?: Record<string, unknown> | null;
  avatar_url?: string;
  created_at: string;
  updated_at: string;
  /** Hydrated by queries that embed `contact_tags(tags(*))` (e.g. the
   *  Inbox conversation list, for tag filtering). Absent otherwise. */
  tags?: Tag[];
}

export interface Tag {
  id: string;
  user_id: string;
  name: string;
  color: string;
  created_at: string;
}

export interface ContactTag {
  id: string;
  contact_id: string;
  tag_id: string;
}

export interface CustomField {
  id: string;
  user_id: string;
  /** Tenancy key — NOT NULL since migration 017. */
  account_id: string;
  field_name: string;
  field_type: string;
  field_options?: Record<string, unknown>;
  created_at: string;
}

export interface ContactCustomValue {
  id: string;
  contact_id: string;
  custom_field_id: string;
  value?: string;
}

export interface ContactNote {
  id: string;
  contact_id: string;
  user_id: string;
  note_text: string;
  created_at: string;
}

export type ConversationStatus = 'open' | 'pending' | 'closed';

export interface Conversation {
  id: string;
  user_id: string;
  contact_id: string;
  status: ConversationStatus;
  assigned_agent_id?: string;
  last_message_text?: string;
  last_message_at?: string;
  unread_count: number;
  created_at: string;
  updated_at: string;
  contact?: Contact;
  /**
   * AI auto-reply state for this thread (migration 029 + 033):
   *  - `ai_autoreply_disabled` — the bot is paused here (a human took
   *    over, or the model handed off). Sticky until re-enabled.
   *  - `ai_reply_count` — how many times the bot has auto-replied,
   *    checked against the account's per-conversation cap.
   *  - `ai_handoff_summary` — short internal note the bot wrote when it
   *    handed off, shown to whoever takes the thread over.
   */
  ai_autoreply_disabled?: boolean;
  ai_reply_count?: number;
  ai_handoff_summary?: string | null;
  /** Messaging channel this conversation is on (migration 039, widened to include 'facebook' in migration 041). Defaults to 'whatsapp' for every pre-existing row. */
  channel?: 'whatsapp' | 'instagram' | 'facebook';
  /** Which WhatsApp connection owns this thread (migration 050). Null for non-WhatsApp channels. */
  whatsapp_config_id?: string | null;
}

// ============================================================
// Notifications (migration 027, 'ai_key_invalid' added in 079)
// ============================================================

export type NotificationType = 'conversation_assigned' | 'ai_key_invalid';

export interface Notification {
  id: string;
  account_id: string;
  /** Recipient — the agent this notification is for. */
  user_id: string;
  type: NotificationType;
  conversation_id?: string;
  contact_id?: string;
  /** Who triggered it. Null when an automation/system assigned it. */
  actor_user_id?: string;
  title: string;
  body?: string;
  read_at?: string;
  created_at: string;
}

export type SenderType = 'customer' | 'agent' | 'bot';
export type ContentType =
  | 'text'
  | 'image'
  | 'document'
  | 'audio'
  | 'video'
  | 'location'
  | 'template'
  /** Customer tapped a reply button or list row on a message we sent. */
  | 'interactive'
  /** An internal system note (e.g. why the AI handed a conversation off
   *  to a human) — never sent to the customer over any channel, and
   *  excluded from the AI's own conversation context. Migration 083. */
  | 'internal_note';
export type MessageStatus = 'sending' | 'sent' | 'delivered' | 'read' | 'failed';

export interface Message {
  id: string;
  conversation_id: string;
  sender_type: SenderType;
  sender_id?: string;
  content_type: ContentType;
  content_text?: string;
  media_url?: string;
  template_name?: string;
  message_id?: string;
  status: MessageStatus;
  created_at: string;
  reply_to_message_id?: string;
  /**
   * Only set when `content_type === 'interactive'` — the stable id of
   * the button or list row the customer tapped. The Flows engine uses
   * this to route the next node; the inbox bubble uses it as a styling
   * cue (renders with a "↩ button reply" affordance).
   */
  interactive_reply_id?: string;
  /**
   * Structured payload of an OUTBOUND interactive message (reply
   * buttons or list) we sent. Lets the thread re-render the buttons /
   * rows, not just the body text. Only set when `content_type ===
   * 'interactive'` and `sender_type` is agent/bot. Migration 035.
   */
  interactive_payload?: InteractiveMessagePayload;
  /**
   * True when the AI auto-reply bot generated + sent this message (as
   * opposed to a human agent or a deterministic Flow/automation send,
   * which all share `sender_type='bot'`/`'agent'`). Drives the "AI"
   * badge in the inbox. Migration 033.
   */
  ai_generated?: boolean;
}

export type ReactionActor = 'customer' | 'agent';

export interface MessageReaction {
  id: string;
  message_id: string;
  conversation_id: string;
  actor_type: ReactionActor;
  actor_id?: string;
  emoji: string;
  created_at: string;
}

export interface WhatsAppConfig {
  id: string;
  user_id: string;
  provider: 'meta' | 'zernio';
  phone_number_id?: string;
  waba_id?: string;
  access_token?: string;
  verify_token?: string;
  zernio_api_key?: string;
  zernio_account_id?: string;
  status: 'connected' | 'disconnected';
  connected_at?: string;
  /**
   * Set when POST /{phone_number_id}/register last succeeded. NULL
   * means the number was saved but never actually subscribed for
   * webhooks on Meta's side — inbound events will be silently lost.
   * Meta-only — a Zernio-provider row never sets this (Zernio owns
   * its own subscription server-side).
   */
  registered_at?: string;
  /** Set when POST /{waba_id}/subscribed_apps last succeeded. Meta-only. */
  subscribed_apps_at?: string;
  /** Last error from /register; cleared on success. Meta-only. */
  last_registration_error?: string;
}

export interface InstagramConfig {
  id: string;
  user_id: string;
  provider: 'meta' | 'zernio';
  ig_account_id?: string;
  page_id?: string;
  ig_username?: string;
  access_token?: string;
  verify_token?: string;
  zernio_api_key?: string;
  zernio_account_id?: string;
  status: 'connected' | 'disconnected';
  connected_at?: string;
  last_connection_error?: string;
}

/** Facebook has no direct-Meta path in wacrm — always a Zernio connection. */
export interface FacebookConfig {
  id: string;
  user_id: string;
  zernio_api_key: string;
  zernio_account_id: string;
  fb_page_name?: string;
  status: 'connected' | 'disconnected';
  connected_at?: string;
  last_connection_error?: string;
}

// Raw Meta status enum. We persist this verbatim from Meta (sync + webhook)
// rather than collapsing to a local TitleCase set — distinctions like
// PAUSED vs DISABLED vs IN_APPEAL drive the edit/resubmit/delete flows.
// DRAFT is the local-only state before the row is submitted to Meta.
export type MessageTemplateStatus =
  | 'DRAFT'
  | 'PENDING'
  | 'APPROVED'
  | 'REJECTED'
  | 'PAUSED'
  | 'DISABLED'
  | 'IN_APPEAL'
  | 'PENDING_DELETION';

export type TemplateButton =
  | { type: 'QUICK_REPLY'; text: string }
  | { type: 'URL'; text: string; url: string; example?: string }
  | { type: 'PHONE_NUMBER'; text: string; phone_number: string }
  | { type: 'COPY_CODE'; text: string; example: string };

export interface TemplateSampleValues {
  body?: string[];
  header?: string[];
}

export interface MessageTemplate {
  id: string;
  user_id: string;
  name: string;
  category: 'Marketing' | 'Utility' | 'Authentication';
  language?: string;
  header_type?: 'text' | 'image' | 'video' | 'document';
  header_content?: string;
  header_handle?: string;
  header_media_url?: string;
  body_text: string;
  footer_text?: string;
  buttons?: TemplateButton[];
  sample_values?: TemplateSampleValues;
  status?: MessageTemplateStatus;
  meta_template_id?: string;
  rejection_reason?: string;
  quality_score?: 'GREEN' | 'YELLOW' | 'RED';
  submission_error?: string;
  last_submitted_at?: string;
  created_at: string;
}

export interface Pipeline {
  id: string;
  user_id: string;
  name: string;
  created_at: string;
}

export interface PipelineStage {
  id: string;
  pipeline_id: string;
  name: string;
  position: number;
  color: string;
  /** "Venta cerrada" — a deal landing here sets status='won' and fires deal.won. */
  is_won: boolean;
  created_at: string;
}

export type DealStatus = 'open' | 'won' | 'lost';

export interface Deal {
  id: string;
  user_id: string;
  pipeline_id: string;
  stage_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved.
   */
  contact_id: string | null;
  conversation_id?: string;
  assigned_to?: string;
  title: string;
  value: number;
  currency?: string;
  notes?: string;
  expected_close_date?: string;
  status?: DealStatus;
  created_at: string;
  updated_at?: string;
  contact?: Contact;
  stage?: PipelineStage;
  assignee?: Profile;
}

// ============================================================
// Product catalog + Quotes (migration 053)
// ============================================================

export interface Product {
  id: string;
  account_id: string;
  user_id: string;
  name: string;
  description?: string | null;
  price: number;
  /** Optional flat installation fee for the base price (migration 076). */
  installation_cost?: number | null;
  image_url?: string | null;
  is_active: boolean;
  /** Catalog category (migration 106) — null for uncategorised / generic
   *  accounts. */
  category_id?: string | null;
  created_at: string;
  updated_at: string;
  /** Up to 2 additional priced options (migration 075) — e.g. a
   *  size/color that costs more than the base price. Not present on
   *  every fetch; routes that don't need them omit the join. */
  price_options?: ProductPriceOption[];
  /** Per-date room rates (migration 106) — only the `hotel` vertical
   *  populates these. Absent on fetches that don't join them. */
  rates?: ProductRateRow[];
}

/** A row of `product_rates` (migrations 106 + 108 + 111). */
export interface ProductRateRow {
  id: string;
  account_id: string;
  product_id: string;
  /** Which day of the week this price applies to (migration 111). */
  day_of_week: 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun';
  /** standard = base · couple = 2 guests · group = 3+ guests (migration 108). */
  occupancy: 'standard' | 'couple' | 'group';
  price: number;
  date_from: string | null;
  date_to: string | null;
  position: number;
  created_at: string;
  updated_at: string;
}

/** A catalog category (migration 106). */
export interface ProductCategory {
  id: string;
  account_id: string;
  name: string;
  position: number;
  created_at: string;
  updated_at: string;
}

/**
 * One additional priced variant of a product (migration 075) — e.g.
 * "Talla M / Azul" at a different price than the base, optionally with
 * its own installation cost and its own extra photos. A product may
 * have zero, one, or two of these (capped client-side in
 * product-form.tsx), on top of the base `Product.price`.
 */
export interface ProductPriceOption {
  id: string;
  account_id: string;
  product_id: string;
  label: string;
  price: number;
  installation_cost?: number | null;
  image_urls: string[];
  position: number;
  created_at: string;
  updated_at: string;
}

export type QuoteStatus = 'draft' | 'sent' | 'accepted' | 'rejected' | 'expired';

export interface QuoteItem {
  id: string;
  quote_id: string;
  /** Null for a free-form item — only a human can create one; the AI's
   *  create_quote action only ever references catalog products. */
  product_id: string | null;
  /** Which priced option (if any) this line used — see ProductPriceOption. */
  product_price_option_id?: string | null;
  description: string;
  unit_price: number;
  quantity: number;
  line_total: number;
  position: number;
  created_at: string;
}

export interface Quote {
  id: string;
  account_id: string;
  user_id: string;
  contact_id: string;
  deal_id: string | null;
  /** Optional (migration 082) — no company is required to collect a
   *  customer's tax ID/email for a quote; null when not given. */
  customer_nit: string | null;
  customer_email: string | null;
  customer_phone: string;
  customer_address: string;
  currency: string;
  subtotal: number;
  total: number;
  status: QuoteStatus;
  pdf_url?: string | null;
  sent_at?: string | null;
  /** True while waiting for the contact's WhatsApp messaging window to
   *  open so the auto-send flow can deliver its PDF — see migration
   *  057_quote_auto_send.sql. */
  auto_send_pending?: boolean;
  created_at: string;
  updated_at: string;
  contact?: Contact;
  items?: QuoteItem[];
}

export type BroadcastStatus = 'draft' | 'scheduled' | 'sending' | 'sent' | 'failed';
export type RecipientStatus = 'pending' | 'sent' | 'delivered' | 'read' | 'replied' | 'failed';

export interface Broadcast {
  id: string;
  user_id: string;
  name: string;
  template_name: string;
  template_language: string;
  template_variables?: Record<string, unknown>;
  audience_filter?: Record<string, unknown>;
  scheduled_at?: string;
  status: BroadcastStatus;
  total_recipients: number;
  sent_count: number;
  delivered_count: number;
  read_count: number;
  replied_count: number;
  failed_count: number;
  /** WhatsApp connection used to send this broadcast (migration 050). */
  whatsapp_config_id?: string | null;
  /**
   * Set while a server-side delivery pass is fanning out, NULL when
   * idle. Claimed with a conditional UPDATE so two resumes can't both
   * send. Added in migration 038.
   */
  delivery_locked_at?: string | null;
  created_at: string;
}

export interface BroadcastRecipient {
  id: string;
  broadcast_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved; the
   * UI renders "Unknown" for orphaned rows.
   */
  contact_id: string | null;
  status: RecipientStatus;
  sent_at?: string;
  delivered_at?: string;
  read_at?: string;
  replied_at?: string;
  error_message?: string;
  /**
   * Meta's message id, persisted when the broadcast send succeeds so
   * the webhook can mirror status updates back onto the recipient row.
   * Added in migration 003.
   */
  whatsapp_message_id?: string;
  /**
   * Positional body values for this recipient's template send
   * ({{1}}, {{2}}, …), frozen when the broadcast was planned so a
   * server-side resume reproduces the original pass exactly.
   * Added in migration 038; null on rows created before it.
   */
  template_params?: string[] | null;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Automations (migration 006)
// ============================================================

export type AutomationTriggerType =
  | 'new_message_received'
  | 'first_inbound_message'
  | 'keyword_match'
  | 'new_contact_created'
  | 'conversation_assigned'
  | 'tag_added'
  | 'time_based'
  /** Customer tapped a reply button / list row whose id matches; lets
   *  multi-step menus be chained across automations. */
  | 'interactive_reply';

export type AutomationStepType =
  | 'send_message'
  | 'send_buttons'
  | 'send_list'
  | 'send_template'
  | 'add_tag'
  | 'remove_tag'
  | 'assign_conversation'
  | 'update_contact_field'
  | 'create_deal'
  | 'move_deal'
  | 'create_task'
  | 'wait'
  | 'condition'
  | 'send_webhook'
  | 'close_conversation';

export type AutomationLogStatus = 'success' | 'partial' | 'failed';

export interface KeywordMatchTriggerConfig {
  keywords: string[];
  /**
   * `contains` (the default) is a raw substring test, so a short keyword
   * matches inside longer words — "k" fires on "thanks". `word` is the
   * boundary-aware alternative added for issue #409; see
   * `matchesWholeWord` in `@/lib/automations/engine` for its exact
   * semantics. Flows carry their own keyword config and stay
   * substring-only (`@/lib/flows/types`).
   */
  match_type: 'exact' | 'contains' | 'word';
  case_sensitive?: boolean;
}

export interface TagTriggerConfig {
  tag_id: string;
}

export interface TimeBasedTriggerConfig {
  /** Cron expression or simple HH:mm string; engine can accept either. */
  schedule: string;
  timezone?: string;
}

export interface InteractiveReplyTriggerConfig {
  /** Button / list-row ids to match, exact. Any one matching fires. */
  reply_ids: string[];
}

export type AutomationTriggerConfig =
  | Record<string, never>
  | KeywordMatchTriggerConfig
  | TagTriggerConfig
  | TimeBasedTriggerConfig
  | InteractiveReplyTriggerConfig
  | Record<string, unknown>;

export interface SendMessageStepConfig {
  text: string;
}

/**
 * `send_buttons` / `send_list` step configs carry the full interactive
 * payload (same shape stored on messages + quick replies). `kind` is
 * implied by the step_type but kept on the payload for a uniform shape.
 */
export type SendButtonsStepConfig = InteractiveMessagePayload;
export type SendListStepConfig = InteractiveMessagePayload;

export interface SendTemplateStepConfig {
  template_name: string;
  language?: string;
  variables?: Record<string, string>;
}

export interface TagStepConfig {
  tag_id: string;
}

export interface AssignConversationStepConfig {
  mode: 'specific' | 'round_robin';
  agent_id?: string;
}

export interface UpdateContactFieldStepConfig {
  /**
   * Either a built-in contact column (`name` | `email` | `company`) or a
   * custom field encoded as `custom:<custom_field_id>`. The `custom:` prefix
   * is how the engine distinguishes a `contact_custom_values` write from a
   * direct `contacts` column update. Older configs store the bare column name,
   * so this stays backward compatible.
   */
  field: string;
  /** Supports `{{ vars.* }}` / `{{ message.text }}` interpolation at runtime. */
  value: string;
}

export interface CreateDealStepConfig {
  pipeline_id: string;
  stage_id: string;
  title: string;
  value?: number;
}

export interface MoveDealStepConfig {
  /**
   * Target stage — no `pipeline_id` needed, unlike `create_deal`: the
   * stage's own pipeline is looked up server-side, and the contact's
   * open deal must already belong to it (see `moveDeal` in
   * `@/lib/pipelines/move-deal`). No `deal_id` either — this always
   * moves the contact's own currently-open deal, resolved the same
   * way the auto-reply bot's autonomous stage progression does.
   */
  stage_id: string;
}

export interface CreateTaskStepConfig {
  /** Task title. Supports `{{ vars.* }}` / `{{ message.text }}`. */
  title: string;
  /** Optional notes. Same interpolation as `title`. */
  notes?: string;
  /**
   * Who owns the task: `''` / absent = unassigned, `'author'` = the
   * automation's own author, anything else = a member `user_id`.
   */
  assignee?: string;
  /** Hours from now until the task is due. `0` / absent = no due date
   *  (and therefore no reminder push). */
  due_in_hours?: number;
}

export interface WaitStepConfig {
  amount: number;
  unit: 'minutes' | 'hours' | 'days';
}

export type ConditionSubject =
  | 'contact_field'
  | 'tag_presence'
  | 'message_content'
  | 'time_of_day'
  | 'message_count';

export interface ConditionStepConfig {
  subject: ConditionSubject;
  /**
   * e.g. field name, tag id, substring, or "HH:mm-HH:mm" depending on
   * subject. For `message_count`, one of the comparison operators
   * `>` | `>=` | `<` | `<=` | `==`, compared against `value` (a
   * stringified integer) — total messages (both directions) in the
   * conversation so far.
   */
  operand?: string;
  /** For contact_field equals / message_content contains / message_count
   *  comparisons — the value being compared against. */
  value?: string;
}

export interface SendWebhookStepConfig {
  url: string;
  headers?: Record<string, string>;
  body_template?: string;
}

export type AutomationStepConfig =
  | SendMessageStepConfig
  | SendButtonsStepConfig
  | SendListStepConfig
  | SendTemplateStepConfig
  | TagStepConfig
  | AssignConversationStepConfig
  | UpdateContactFieldStepConfig
  | CreateDealStepConfig
  | MoveDealStepConfig
  | CreateTaskStepConfig
  | WaitStepConfig
  | ConditionStepConfig
  | SendWebhookStepConfig
  | Record<string, never>
  | Record<string, unknown>;

export interface Automation {
  id: string;
  /** Account tenancy key — every automation belongs to one account
   *  (migration 017 made the column NOT NULL). The engine looks up
   *  active automations by this field on inbound webhook events. */
  account_id: string;
  /** Original author. Used for log audit + outbound message
   *  sender-of-record, never for tenancy isolation. */
  user_id: string;
  name: string;
  description?: string;
  trigger_type: AutomationTriggerType;
  trigger_config: AutomationTriggerConfig;
  is_active: boolean;
  execution_count: number;
  last_executed_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface AutomationStep {
  id: string;
  automation_id: string;
  parent_step_id?: string | null;
  branch?: 'yes' | 'no' | null;
  step_type: AutomationStepType;
  step_config: AutomationStepConfig;
  position: number;
  created_at: string;
}

export interface AutomationLogStepResult {
  step_id: string;
  step_type: AutomationStepType;
  status: 'success' | 'skipped' | 'failed';
  detail?: string;
}

export interface AutomationLog {
  id: string;
  automation_id: string;
  user_id: string;
  contact_id: string | null;
  trigger_event: string;
  steps_executed: AutomationLogStepResult[];
  status: AutomationLogStatus;
  error_message?: string | null;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Quick replies — reusable snippets (migration 035)
// ============================================================

export type QuickReplyKind = 'text' | 'interactive';

export interface QuickReply {
  id: string;
  /** Account tenancy key — shared across all members of the account. */
  account_id: string;
  /** Author / audit only. */
  user_id: string;
  title: string;
  kind: QuickReplyKind;
  /** Set when `kind === 'text'`. */
  content_text?: string | null;
  /** Set when `kind === 'interactive'`. */
  interactive_payload?: InteractiveMessagePayload | null;
  created_at: string;
  updated_at: string;
}
